Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true
Mappings:
  RegionMap:
    us-east-1:
      AMALINUX: ami-013be31976ca2c322
    us-east-2:
      AMALINUX: ami-0b59bfac6be064b78
    us-west-1:
      AMALINUX: ami-01beb64058d271bc4
    us-west-2:
      AMALINUX: ami-061e7ebbc234015fe
    ca-central-1:
      AMALINUX: ami-076b4adb3f90cd384
    eu-central-1:
      AMALINUX: ami-02ea8f348fa28c108
    eu-west-1:
      AMALINUX: ami-0a5e707736615003c
    eu-west-2:
      AMALINUX: ami-0274e11dced17bb5b
    eu-west-3:
      AMALINUX: ami-051707cdba246187b
    ap-northeast-1:
      AMALINUX: ami-0a2de1c3b415889d2
    ap-northeast-2:
      AMALINUX: ami-0b4fdb56a00adb616
    ap-south-1:
      AMALINUX: ami-06bcd1131b2f55803
    ap-southeast-1:
      AMALINUX: ami-085fd1bd447be68e8
    ap-southeast-2:
      AMALINUX: ami-0b8dea0e70b969adc
    sa-east-1:
      AMALINUX: ami-0112d42866980b373
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: "5"
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] # Dynamic mapping + Pseudo Parameter
      DBName: !Ref DatabaseName
      Engine: MariaDB
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: AdvancedCFN
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            systemctl start httpd
            systemctl enable httpd
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -zxvf latest.tar.gz --strip 1
            rm latest.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Open Ports 22 and 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
  S3Bucket:
    Type: "AWS::S3::Bucket"

Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub http://${EC2.PublicDnsName}
