AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: SSH Configuration
        Parameters:
          - KeyName
          - SSHLocation
      -
        Label:
          default: Application Configuration
        Parameters:
          - ApplicationSize
          - DesiredEC2Capacity
          - MaxEC2Instances
      -
        Label:
          default: ECS Configuration
        Parameters:
          - DesiredServicesNumber
          - MaxServicesNumber
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances.
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  DesiredEC2Capacity:
    Type: Number
    Default: 1
    Description: Number of EC2 instances to launch in your ECS cluster.
  MaxEC2Instances:
    Type: Number
    Default: 1
    Description: Maximum number of EC2 instances that can be launched in your ECS cluster.
  DesiredServicesNumber:
    Type: Number
    Default: 2
    Description: Number of ECS services to launch in your ECS cluster.
  MaxServicesNumber:
    Type: Number
    Default: 4
    Description: Maximum number of ECS services that can be launched in your ECS cluster.
  ApplicationSize:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Application Size (S,M,L)
Mappings:
  AWSRegionToAMI:
    us-east-1:
      ECSAMI: ami-0a6b7e0cc0b1f464f
    us-east-2:
      ECSAMI: ami-037a92bf1efdb11a2
    us-west-1:
      ECSAMI: ami-0184f498956de7db5
    us-west-2:
      ECSAMI: ami-0c1f4871ebaae6d86
    ca-central-1:
      ECSAMI: ami-02c80e9173258d289
    eu-west-1:
      ECSAMI: ami-0acc9f8be17a41897
    eu-west-2:
      ECSAMI: ami-0b5225210a12d9951
    eu-west-3:
      ECSAMI: ami-0caadc4f0db31a303
    eu-central-1:
      ECSAMI: ami-055aa9664ef169e25
    ap-northeast-1:
      ECSAMI: ami-0c38293d60d98af86
    ap-northeast-2:
      ECSAMI: ami-0bdc871079baf9649
    ap-southeast-1:
      ECSAMI: ami-0e28ff4e3f1776d86
    ap-southeast-2:
      ECSAMI: ami-0eed1c915ea891aca
    ap-south-1:
      ECSAMI: ami-0b7c3be99909df6ef
    sa-east-1:
      ECSAMI: ami-078146697425f25a7
  InstanceSize:
    DEV:
      EC2: t2.micro
      DB: db.t2.micro
    SMALL:
      EC2: t3.small
      DB: db.t2.small
    MEDIUM:
      EC2: t3.medium
      DB: db.t2.medium
    LARGE:
      EC2: m5.large
      DB: db.m5.large
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Security Group
      VpcId: !ImportValue shared-vpc-id
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  # postgres port 6379
  ECSSecurityGroupPostgresIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ECSSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref ECSSecurityGroup
  # redis port 6379
  ECSSecurityGroupRedisIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ECSSecurityGroup
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      SourceSecurityGroupId: !Ref ECSSecurityGroup
  # ephermeral ports 32768 - 61000
  ECSSecurityGroupALBIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ECSSecurityGroup
      IpProtocol: tcp
      FromPort: 32768
      ToPort: 61000
      SourceSecurityGroupId: !Ref ECSSecurityGroup
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "ECSLogGroup-${AWS::StackName}"
      RetentionInDays: 14
  ECSApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 30
      Subnets:
        - !ImportValue shared-vpc-public-subnet1
        - !ImportValue shared-vpc-public-subnet2
      SecurityGroups:
        - !Ref ECSSecurityGroup
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup
      LoadBalancerArn: !Ref ECSApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ECSTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - /
      ListenerArn: !Ref ALBListener
      Priority: 1
  ECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ECSApplicationLoadBalancer
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !ImportValue shared-vpc-id
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue shared-vpc-public-subnet1
        - !ImportValue shared-vpc-public-subnet2
      LaunchConfigurationName: !Ref ClusterLaunchConfiguration
      MinSize: 1
      MaxSize: !Ref MaxEC2Instances
      DesiredCapacity: !Ref DesiredEC2Capacity
    CreationPolicy:
      ResourceSignal:
        Count: !Ref DesiredServicesNumber
        Timeout: PT15M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
  ClusterLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", ECSAMI]
      SecurityGroups:
        - !Ref ECSSecurityGroup
      InstanceType: !FindInMap [InstanceSize, !Ref ApplicationSize, EC2]
      IamInstanceProfile: !ImportValue cluster-instance-profile
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ECSAutoScalingGroup --region ${AWS::Region}
  RailsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}-rails-on-ecs"
      ContainerDefinitions:
        -
          Name: rails-app
          Cpu: 10
          Essential: true
          Image: httpd:2.4-alpine
          Memory: 300
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: rails-on-ecs
          MountPoints:
            - ContainerPath: /usr/local/apache2/htdocs
              SourceVolume: static-files
          PortMappings:
            - ContainerPort: 80
        -
          Name: busybox
          Cpu: 10
          Command: ['/bin/sh -c "while true; do echo ''<html> <head> <title>Amazon ECS
              Sample App</title> <style>body {margin-top: 40px; background-color: #333; font-family: Helvetica, Helvetica Neue, Arial;}
              </style> </head><body> <div style=color:white;text-align:center> <h1>Amazon
              ECS Sample App</h1> <h2>Congratulations!</h2> <p>Your application is now
              running on a container in Amazon ECS.</p>'' > top; /bin/date > date ;
              echo ''</div></body></html>'' > bottom; cat top date bottom > /usr/local/apache2/htdocs/index.html
              ; sleep 1; done"']
          EntryPoint: [sh, -c]
          Essential: false
          Image: busybox
          Memory: 200
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: rails-on-ecs
          VolumesFrom:
            - SourceContainer: rails-app
      Volumes:
        - Name: static-files
  RailsService:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredServicesNumber
      LoadBalancers:
        -
          ContainerName: rails-app
          ContainerPort: 80
          TargetGroupArn: !Ref ECSTargetGroup
      Role: !ImportValue ecs-service-role
      TaskDefinition: !Ref RailsTaskDefinition
  ServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxServiceNumber
      MinCapacity: 1
      ResourceId: !Sub "service/${ECSCluster}/${RailsService.Name}"
      RoleARN: !ImportValue autoscaling-role-arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
  ServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-ServiceScalingPolicy"
      PolicyType: StepScaling
      ScalingTargetId: !Ref ServiceScalingTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: PercentChangeInCapacity
        Cooldown: 60
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 200
  ALB500sAlarmScaleUp:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: 1
      Statistic: Average
      Threshold: 10
      AlarmDescription: Alarm if our ALB generates too many HTTP 500s
      Period: 60
      AlarmActions:
        - !Ref ServiceScalingPolicy
      Namespace: AWS/ApplicationELB
      Dimensions:
        - Name: LoadBalancer
          Value: !GetAtt [ECSApplicationLoadBalancer, LoadBalancerFullName]
      ComparisonOperator: GreaterThanThreshold
Outputs:
  ApplicationURL:
    Description: Your Application URL
    Value: !Sub "http://${ECSApplicationLoadBalancer.DNSName}"
