version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data

  web:
    build: rails-on-ecs
    depends_on:
      - postgres
    environment:
    # - DATABASE_URL=postgresql://user:password@host:5432/databse?encoding=utf8&pool=5&timeout=5000
      - CACHE_URL=redis://redis:6379
      - JOB_WORKER_URL=redis://redis:6379
      - WEB_CONCURRENCY=1
      - MAX_THREADS=1
    entrypoint: /db-migrations.sh
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - static:/usr/src/app/public

  nginx:
    build: rails-nginx
    depends_on:
      - web
    ports:
      - 3000:80
    volumes:
      - static:/usr/share/nginx/html

volumes:
  postgres:
  redis:
  static: