version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: rails-on-ecs
    depends_on:
      - postgres
    entrypoint: /db-migrations.sh
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000

volumes:
  postgres: