version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: rails-on-ecs
    entrypoint: /docker-entrypoint.sh
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  nginx:
    build: rails-nginx
    depends_on:
      - web
    ports:
      - 3000:80

volumes:
  postgres: